version: '2'

services:
  apache-site-1:
    image: bitnami/apache:latest
    volumes:
    - ./app:/app
    - ./bitnami.conf:/opt/bitnami/apache/conf/bitnami/bitnami.conf
    networks:
      site1:
        aliases:
          - apache
  apache-exporter-site-1:
    image: bitnami/apache-exporter:latest
    command:
    - --scrape_uri=http://apache:8080/server-status/?auto
    networks:
      site1:
        aliases:
          - apache-exporter
  ziti-host-site-1:
    image: openziti/ziti-host:0.21.5
    volumes:
      - ./target1.prometheus.scrape.target.json:/ziti-edge-tunnel/ziti_id.json
    networks:
      site1:
  loadgen-site-1:
    image: alpine/curl
    command: [ "/bin/sh", "-c", "while true; do sleep 1; curl -s 'http://apache:8080/server-status/?auto' > /dev/null; done" ]
    networks:
      site1:
      
  apache-site-2:
    image: bitnami/apache:latest
    volumes:
    - ./app:/app
    - ./bitnami.conf:/opt/bitnami/apache/conf/bitnami/bitnami.conf
    networks:
      site2:
        aliases:
          - apache
  apache-exporter-site-2:
    image: bitnami/apache-exporter:latest
    command:
    - --scrape_uri=http://apache:8080/server-status/?auto
    networks:
      site2:
        aliases:
          - apache-exporter
  ziti-host-site-2:
    image: openziti/ziti-host:0.21.5
    volumes:
      - ./target2.prometheus.scrape.target.json:/ziti-edge-tunnel/ziti_id.json
    networks:
      site2:
  loadgen-site-2:
    image: alpine/curl
    command: [ "/bin/sh", "-c", "while true; do sleep 1; curl -s 'http://apache:8080/server-status/?auto' > /dev/null; curl -s 'http://apache:8080/server-status/?auto' > /dev/null; done" ]
    networks:
      site2:
      
  apache-site-3:
    image: bitnami/apache:latest
    volumes:
    - ./app:/app
    - ./bitnami.conf:/opt/bitnami/apache/conf/bitnami/bitnami.conf
    networks:
      site3:
        aliases:
          - apache
  apache-exporter-site-3:
    image: bitnami/apache-exporter:latest
    command:
    - --scrape_uri=http://apache:8080/server-status/?auto
    networks:
      site3:
        aliases:
          - apache-exporter
  ziti-host-site-3:
    image: openziti/ziti-host:0.21.5
    volumes:
      - ./target3.prometheus.scrape.target.json:/ziti-edge-tunnel/ziti_id.json
    networks:
      site3:
  loadgen-site-3:
    image: alpine/curl
    command: [ "/bin/sh", "-c", "while true; do sleep 1; curl -s 'http://apache:8080/server-status/?auto' > /dev/null; curl -s 'http://apache:8080/server-status/?auto' > /dev/null; curl -s 'http://apache:8080/server-status/?auto' > /dev/null; done" ]
    networks:
      site3:
      
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - site1
      - site2
      - site3

networks:
  site1:
  site2:
  site3: